### ISSUE TITLE
Add docs.rs and crates.io badges to Readme

### ISSUE THREAD

**Issue by jasongrlicky** [pcsm/handlebox#3]

**Comment by Atul9** [comment]
@jasongrlicky I would like to work on this

**Comment by jasongrlicky** [comment]
Hey @Atul9, that would be fantastic, thank you! Just open a pull request and I'll merge it in no problems. 👏 

I intend to switch the license of this project to be dual licensed under MIT/Apache to better fit in with the Rust library ecosystem. According to my understanding of that, I need to get you to agree that you license your contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option. Would you mind commenting to confirm that you agree to this before opening the pull request?

Thanks again!

**Comment by Atul9** [comment]
I agree to license my contributions under dual MIT/Apache-2.0 license
